{
	"id": "114961",
	"key": "AC-2212",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "3",
			"description": "The problem is a duplicate of an existing issue.",
			"name": "Duplicate"
		},
		"resolutiondate": "2013-05-26T07:25:15.000+0000",
		"created": "2013-05-26T07:20:57.000+0000",
		"labels": [
			"android",
			"defect",
			"studio3"
		],
		"versions": [],
		"issuelinks": [
			{
				"id": "29073",
				"type": {
					"id": "10002",
					"name": "Duplicate",
					"inward": "is duplicated by",
					"outward": "duplicates"
				},
				"inwardIssue": {
					"id": "114690",
					"key": "TIMOB-13944",
					"fields": {
						"summary": "Android: build: TypeError: argument of type 'NoneType' is not iterable",
						"status": {
							"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
							"name": "Closed",
							"id": "6",
							"statusCategory": {
								"id": 3,
								"key": "done",
								"colorName": "green",
								"name": "Done"
							}
						},
						"priority": {
							"name": "Critical",
							"id": "1"
						},
						"issuetype": {
							"id": "1",
							"description": "A problem which impairs or prevents the functions of the product.",
							"name": "Bug",
							"subtask": false
						}
					}
				}
			}
		],
		"assignee": {
			"name": "mpmiranda",
			"key": "mpmiranda",
			"displayName": "Mauro Parra-Miranda",
			"active": true,
			"timeZone": "America/Mexico_City"
		},
		"updated": "2016-03-08T07:41:12.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "14551",
				"name": "Studio",
				"description": "Please enter tickets related to Titanium Studio here."
			}
		],
		"description": "I have recently started seeing these in the console when I try to either run in the emulator or deploy to the device:\r\n\r\n[TRACE] Writing out AndroidManifest.xml\r\n[ERROR] Exception occured while building Android project:\r\n[ERROR] Traceback (most recent call last):\r\n[ERROR]   File \"C:\\Users\\Nedim\\AppData\\Roaming\\Titanium\\mobilesdk\\win32\\3.0.2.GA\\android\\builder.py\", line 2412, in <module>\r\n[ERROR]     builder.build_and_run(True, avd_id, device_args=device_args, debugger_host=debugger_host)\r\n[ERROR]   File \"C:\\Users\\Nedim\\AppData\\Roaming\\Titanium\\mobilesdk\\win32\\3.0.2.GA\\android\\builder.py\", line 2141, in build_and_run\r\n[ERROR]     self.manifest_changed = self.generate_android_manifest(compiler)\r\n[ERROR]   File \"C:\\Users\\Nedim\\AppData\\Roaming\\Titanium\\mobilesdk\\win32\\3.0.2.GA\\android\\builder.py\", line 1348, in generate_android_manifest\r\n[ERROR]     '-I', self.android_jar], warning_regex=r'skipping')\r\n[ERROR]   File \"C:\\Users\\Nedim\\AppData\\Roaming\\Titanium\\mobilesdk\\win32\\3.0.2.GA\\android\\run.py\", line 38, in run\r\n[ERROR]     print \"[DEBUG] %s\" % subprocess.list2cmdline(args_to_log)\r\n[ERROR]   File \"C:\\Dev\\titanium\\plugins\\com.appcelerator.titanium.python.win32_1.0.0.1338515509\\python\\lib\\subprocess.py\", line 580, in list2cmdline\r\n[ERROR]     needquote = (\" \" in arg) or (\"\\t\" in arg) or not arg\r\n[ERROR] TypeError: argument of type 'NoneType' is not iterable\r\n",
		"attachment": [],
		"flagged": false,
		"summary": "Exception occured while building Android project",
		"creator": {
			"name": "nedim",
			"key": "nedim",
			"displayName": "Nedim Cholich",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "nedim",
			"key": "nedim",
			"displayName": "Nedim Cholich",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Windows 8 64bit\r\nJdk 1.6.0_43 32bit\r\nTitanium Studio 3.1.0.201304151600",
		"comment": {
			"comments": [
				{
					"id": "254018",
					"author": {
						"name": "dsefton",
						"key": "dsefton",
						"displayName": "Daniel Sefton",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Hi Nedim,\r\n\r\nThis is a known issue which we recently fixed (TIMOB-13944). It's due to some breaking changes in Google's r22 Android toolset.\r\n\r\nYou can either use the latest unstable master SDK: http://builds.appcelerator.com.s3.amazonaws.com/index.html#master\r\n\r\nOr modify the stable 3.1 GA SDK:\r\n\r\nBack up and then open the following file:\r\n\t\r\nC:\\Users\\[user]\\AppData\\Roaming\\Titanium\\mobilesdk\\win32\\3.1.0.GA\\android\\androidsdk.py\r\n\r\nReplace its contents with this:\r\n\r\nhttps://raw.github.com/appcelerator/titanium_mobile/master/support/android/androidsdk.py\r\n\r\nResolving as duplicate.",
					"updateAuthor": {
						"name": "dsefton",
						"key": "dsefton",
						"displayName": "Daniel Sefton",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2013-05-26T07:25:15.000+0000",
					"updated": "2013-05-26T07:25:15.000+0000"
				},
				{
					"id": "280902",
					"author": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"body": "Closing since it's a dup. ",
					"updateAuthor": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"created": "2013-11-24T22:07:40.000+0000",
					"updated": "2013-11-24T22:07:40.000+0000"
				}
			],
			"maxResults": 2,
			"total": 2,
			"startAt": 0
		}
	}
}