{
	"id": "100398",
	"key": "AC-1804",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "8",
			"description": "",
			"name": "Needs more info"
		},
		"resolutiondate": "2012-11-26T20:06:23.000+0000",
		"created": "2012-09-04T10:53:38.000+0000",
		"labels": [],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "nsharma",
			"key": "nsharma",
			"displayName": "Nikhil Sharma",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2016-03-08T07:40:42.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [],
		"description": "h3. Steps to Reproduce\nInstalled SDK 2.1.2GA, now I am getting the following errors.\n\nh3. Actual Result\n[ERROR] Exception occured while building Android project:\n[ERROR] Traceback (most recent call last):\n[ERROR]   File \"/home/mobile/.titanium/mobilesdk/linux/2.1.2.GA/android/builder.py\", line 2243, in <module>\n[ERROR]     s.build_and_run(True, avd_id, device_args=device_args)\n[ERROR]   File \"/home/mobile/.titanium/mobilesdk/linux/2.1.2.GA/android/builder.py\", line 2068, in build_and_run\n[ERROR]     launched, launch_failed = self.package_and_deploy()\n[ERROR]   File \"/home/mobile/.titanium/mobilesdk/linux/2.1.2.GA/android/builder.py\", line 1585, in package_and_deploy\n[ERROR]     unsigned_apk = self.create_unsigned_apk(ap_)\n[ERROR]   File \"/home/mobile/.titanium/mobilesdk/linux/2.1.2.GA/android/builder.py\", line 1456, in create_unsigned_apk\n[ERROR]     apk_zip.write(self.classes_dex, 'classes.dex')\n[ERROR]   File \"/usr/lib/python2.7/zipfile.py\", line 1033, in write\n[ERROR]     st = os.stat(filename)\n[ERROR] OSError: [Errno 2] No such file or directory: '/home/mobile/mobile_opal_backup/build/android/bin/classes.dex'\n\n\nh3. Expected Result\nA compiled Android Application",
		"attachment": [
			{
				"id": "30976",
				"filename": ".log",
				"author": {
					"name": "chuckbentley",
					"key": "chuckbentley",
					"displayName": "Chuck Bentley",
					"active": true,
					"timeZone": "America/New_York"
				},
				"created": "2012-09-04T10:53:43.000+0000",
				"size": 20509,
				"mimeType": "text/plain"
			},
			{
				"id": "30977",
				"filename": "diagnostic6065417156668709410.log",
				"author": {
					"name": "chuckbentley",
					"key": "chuckbentley",
					"displayName": "Chuck Bentley",
					"active": true,
					"timeZone": "America/New_York"
				},
				"created": "2012-09-04T10:53:47.000+0000",
				"size": 1660,
				"mimeType": "text/plain"
			}
		],
		"flagged": false,
		"summary": "Exception occured while building Android project:",
		"creator": {
			"name": "chuckbentley",
			"key": "chuckbentley",
			"displayName": "Chuck Bentley",
			"active": true,
			"timeZone": "America/New_York"
		},
		"subtasks": [],
		"reporter": {
			"name": "chuckbentley",
			"key": "chuckbentley",
			"displayName": "Chuck Bentley",
			"active": true,
			"timeZone": "America/New_York"
		},
		"environment": "Titanium Studio 2.1.2",
		"comment": {
			"comments": [
				{
					"id": "218282",
					"author": {
						"name": "nsharma",
						"key": "nsharma",
						"displayName": "Nikhil Sharma",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Hi,\r\nTry to create a default titanium project and check whether you can build that one or not. Are you using any third party modules? ",
					"updateAuthor": {
						"name": "nsharma",
						"key": "nsharma",
						"displayName": "Nikhil Sharma",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2012-09-10T16:26:14.000+0000",
					"updated": "2012-09-10T16:26:14.000+0000"
				},
				{
					"id": "228497",
					"author": {
						"name": "dsefton",
						"key": "dsefton",
						"displayName": "Daniel Sefton",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Will re-open if a response is received.",
					"updateAuthor": {
						"name": "dsefton",
						"key": "dsefton",
						"displayName": "Daniel Sefton",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2012-11-26T20:06:23.000+0000",
					"updated": "2012-11-26T20:06:23.000+0000"
				}
			],
			"maxResults": 2,
			"total": 2,
			"startAt": 0
		}
	}
}