{
	"id": "130269",
	"key": "AC-1000",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "5",
			"description": "All attempts at reproducing this issue failed, or not enough information was available to reproduce the issue. Reading the code produces no clues as to why this behavior would occur. If more information appears later, please reopen the issue.",
			"name": "Cannot Reproduce"
		},
		"resolutiondate": "2014-05-19T06:16:37.000+0000",
		"created": "2014-05-12T04:37:18.000+0000",
		"labels": [],
		"versions": [],
		"issuelinks": [
			{
				"id": "37506",
				"type": {
					"id": "10001",
					"name": "Cloners",
					"inward": "is cloned into",
					"outward": "is cloned from"
				},
				"outwardIssue": {
					"id": "129824",
					"key": "AC-1462",
					"fields": {
						"summary": " \" Unable to securely connect to XXXXXXXXXXX  with the latest TLS. Trying again with TLS1.0. It is highly suggested that the server be updated to the latest TLS support.\" The application does not run in simulator.",
						"status": {
							"description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
							"name": "Resolved",
							"id": "5",
							"statusCategory": {
								"id": 3,
								"key": "done",
								"colorName": "green",
								"name": "Done"
							}
						},
						"issuetype": {
							"id": "1",
							"description": "A problem which impairs or prevents the functions of the product.",
							"name": "Bug",
							"subtask": false
						}
					}
				}
			}
		],
		"assignee": {
			"name": "ragrawal",
			"key": "ragrawal",
			"displayName": "Ritu Agrawal",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2016-03-08T07:37:19.000+0000",
		"status": {
			"description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
			"name": "Resolved",
			"id": "5",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "14548",
				"name": "Titanium SDK & CLI",
				"description": "Please enter tickets related to the MobileSDK here."
			}
		],
		"description": "When tried to run titanium code base using SDK 3.2.2 and IOS SDK 7.1 getting the eerror \" Unable to securely connect to XXXXXXXXXXX  with the latest TLS. Trying again with TLS1.0. It is highly suggested that the server be updated to the latest TLS support.\" The application does not run in simulator.",
		"attachment": [
			{
				"id": "47978",
				"filename": "Screen Shot 2014-05-07 at 10.34.28 am.png",
				"author": {
					"name": "smkteekoy@gmail.com",
					"key": "smkteekoy@gmail.com",
					"displayName": "Sherin Michael",
					"active": true,
					"timeZone": "America/Los_Angeles"
				},
				"created": "2014-05-12T04:37:19.000+0000",
				"size": 93911,
				"mimeType": "image/png"
			}
		],
		"flagged": false,
		"summary": " \" Unable to securely connect to XXXXXXXXXXX  with the latest TLS. Trying again with TLS1.0. It is highly suggested that the server be updated to the latest TLS support.\" The application does not run in simulator.",
		"creator": {
			"name": "smkteekoy@gmail.com",
			"key": "smkteekoy@gmail.com",
			"displayName": "Sherin Michael",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "smkteekoy@gmail.com",
			"key": "smkteekoy@gmail.com",
			"displayName": "Sherin Michael",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Titanium SDK 3.2.2, Mavericks, IOS SDK 7.1 , simulator 7.0 or 7.1",
		"comment": {
			"comments": [
				{
					"id": "304316",
					"author": {
						"name": "smkteekoy@gmail.com",
						"key": "smkteekoy@gmail.com",
						"displayName": "Sherin Michael",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Please follow this test case:\r\n\r\n1.Create a new classic project in Titanium. (In Titanium Studio 3.2.1, SDK 3.2.2. , CLI 3.2.1, IOS SDK 7.1 , Mavericks, Xcode 5.1)\r\n2. Paste the following code in app.js\r\n~~~\r\nmakeCall();\r\n\r\nfunction makeCall() {\r\nvar currentReq = Titanium.Network.createHTTPClient();\r\ncurrentReq.setTimeout(300000);\r\ncurrentReq.onload = function() {\r\n};\r\n\r\ncurrentReq.onerror = function(e)\r\n{ var status =this.status; var statusText = this.statusText; alert(\"Error on Request\",+e.error); }\r\n\r\n;\r\ncurrentReq.open(\"GET\", \"http://developer.appcelerator.com/assets/img/DEV_appteam_photo.png\");\r\ncurrentReq.send();\r\n}\r\n~~~\r\n3. Run the project in IOS 7.1 simulator.\r\n\r\nYou will get the \"status\" 0, which indicates the \"UNSENT\" request.In the console, the given error will be displayed.\r\n\r\nThe same problem is seen even if no request is sent. Just create a new project and try it in the given environment, and you will get the same error regarding connection to the Analytics. I have attached a screen shot of the error .\r\n",
					"updateAuthor": {
						"name": "smkteekoy@gmail.com",
						"key": "smkteekoy@gmail.com",
						"displayName": "Sherin Michael",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2014-05-12T04:39:05.000+0000",
					"updated": "2014-05-12T04:39:05.000+0000"
				},
				{
					"id": "304323",
					"author": {
						"name": "ragrawal",
						"key": "ragrawal",
						"displayName": "Ritu Agrawal",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "I tried your test case and it runs just fine with 3.2.3 GA release. I added an alert to unload function and it gets called correctly. Your test is using HTTP and not HTTPS protocol so TLS or SSL should not be in play anyway.\r\n\r\nNote that your console error is unrelated to your test as it is a warning about sending app analytics to Appcelerator server that uses HTTPS.",
					"updateAuthor": {
						"name": "ragrawal",
						"key": "ragrawal",
						"displayName": "Ritu Agrawal",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2014-05-12T05:45:57.000+0000",
					"updated": "2014-05-12T05:45:57.000+0000"
				},
				{
					"id": "305456",
					"author": {
						"name": "ragrawal",
						"key": "ragrawal",
						"displayName": "Ritu Agrawal",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Resolving this ticket as we cannot reproduce it and the reporter has not followed  up with more information.",
					"updateAuthor": {
						"name": "ragrawal",
						"key": "ragrawal",
						"displayName": "Ritu Agrawal",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2014-05-19T06:16:37.000+0000",
					"updated": "2014-05-19T06:16:37.000+0000"
				}
			],
			"maxResults": 3,
			"total": 3,
			"startAt": 0
		}
	}
}