{
	"id": "174220",
	"key": "AC-6393",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": null,
		"resolutiondate": null,
		"created": "2019-10-04T02:58:37.000+0000",
		"labels": [],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "fhaque",
			"key": "fhaque",
			"displayName": "Fazlul Haque",
			"active": false,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2019-12-23T14:47:25.000+0000",
		"status": {
			"description": "The issue is open and ready for the assignee to start work on it.",
			"name": "Open",
			"id": "1",
			"statusCategory": {
				"id": 2,
				"key": "new",
				"colorName": "blue-gray",
				"name": "To Do"
			}
		},
		"components": [],
		"description": "We are using the debugger tool for android and iOS as recommended from the guide docs:\r\n\r\nhttps://docs.appcelerator.com/platform/latest/?mobile=/guide/Debugging_iOS_Apps_with_3rd-party_Tools-section-src-49160781_DebuggingiOSAppswith3rd-partyTools-Enableuse-jscore-framework\r\n\r\nhttps://docs.appcelerator.com/platform/latest/?mobile=/guide/Debugging_Android_Apps_with_3rd-party_Tools\r\n\r\nThey were working fine on the SDK 7.4.1 for the iOS and 7.5.0 for the android but once we updated to the latest SDK 8 it stopped working and got stuck at the splash screen while debugging to my Samsung device.\r\n\r\nI was wondering if you could help fix this issue asap since our development team is highly relying on this feature/tool to debug and we are also hoping to support the latest the greatest Titanium SDK as well.\r\n\r\nThanks!\r\n",
		"attachment": [],
		"flagged": false,
		"summary": "Debugger Issue on the latest Titanium SDK 8",
		"creator": {
			"name": "kenjorai",
			"key": "kenjorai",
			"displayName": "Kai Lu",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "kenjorai",
			"key": "kenjorai",
			"displayName": "Kai Lu",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Ti SDK 8 +\r\nMac OS Mojave 10.14.6",
		"comment": {
			"comments": [
				{
					"id": "451837",
					"author": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Hello,\r\nThanks for letting us know. Are you experiencing this issue also in 8.2.0.GA? Can you please verify this and let us know?",
					"updateAuthor": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-10-04T06:32:34.000+0000",
					"updated": "2019-10-04T06:32:34.000+0000"
				},
				{
					"id": "451839",
					"author": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Hi Rakhi,\r\n\r\nYes, I am having the issue on the 8.2.0.GA when debugging the app on the device, the simulators work fine though.\r\n\r\nHere is the console log:\r\n\r\n-- Start application log -----------------------------------------------------\r\n[INFO] : \b\b \b Forwarding host port 12345 to device for debugging\r\n[INFO] : \b\b \b Project built successfully in 58s 766ms\r\n\r\n[ERROR] : \b\b \bZygote: isWhitelistProcess - Process is Whitelisted\r\n[WARN] : \b\b \b SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G930F_8.0.0_0018, [-1 -1 -1 -1 0 1]\r\n[INFO] : \b\b \b SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.trimble.workzone\r\n[INFO] : \b\b \b zygote64: no shared libraies, dex_files: 1\r\n[INFO] : \b\b \b TiApplication: (main) [0,0] checkpoint, app created.\r\n[INFO] : \b\b \b MultiDex: VM with version 2.1.0 has multidex support\r\n[INFO] : \b\b \b MultiDex: Installing application\r\n[INFO] : \b\b \b MultiDex: VM has multidex support, MultiDex support library is disabled.\r\n[INFO] : \b\b \b TiApplication: (main) [128,128] Analytics have been disabled\r\n[WARN] : \b\b \b JSDebugger: (main) [209,337] Debugger listening on ws://127.0.0.1:12345/5486aee4-0a97-423d-bc52-db636ebb1b0e\r\n[WARN] : \b\b \b JSDebugger: (main) [1,338] To connect Chrome DevTools, open Chrome to chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:12345/5486aee4-0a97-423d-bc52-db636ebb1b0e\r\n[WARN] : \b\b \b JSDebugger: (main) [0,338] Waiting for debugger to connect for next 60 seconds...\r\n[WARN] : \b\b \b JSDebugger: (WebSocketWorker-40980) [1078,1416] Debugger client connected\r\n[WARN] : \b\b \b JSDebugger: (WebSocketWorker-40981) [44479,45895] Debugger client connected\r\n[WARN] : \b\b \b W/System.err: Uncaught exception in thread \"WebSocketWorker-40981\":java.lang.InternalError: Thread starting during runtime shutdown\r\n[WARN] : \b\b \b W/System.err: \tat java.lang.Thread.nativeCreate(Native Method)\r\n[WARN] : \b\b \b W/System.err: \tat java.lang.Thread.start(Thread.java:733)\r\n[WARN] : \b\b \b W/System.err: \tat org.appcelerator.kroll.runtime.v8.JSDebugger$InspectorAgent.onOpen(JSDebugger.java:172)\r\n[WARN] : \b\b \b W/System.err: \tat org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:541)\r\n[WARN] : \b\b \b W/System.err: \tat org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:701)\r\n[WARN] : \b\b \b W/System.err: \tat org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:240)\r\n[WARN] : \b\b \b W/System.err: \tat org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:161)\r\n[WARN] : \b\b \b W/System.err: \tat org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:781)",
					"updateAuthor": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-10-04T06:49:33.000+0000",
					"updated": "2019-10-04T06:49:33.000+0000"
				},
				{
					"id": "451841",
					"author": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "When debugging on the iOS device, the app gets successfully deployed but when I tap on the app to launch it there is an error pop up in the vs code studio: [titanium-extension] Error processing \"launch\": Unable to discover app",
					"updateAuthor": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-10-04T07:37:07.000+0000",
					"updated": "2019-10-04T07:37:07.000+0000"
				},
				{
					"id": "451844",
					"author": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "OK, so it seems like after I updating my Xcode to 11 and reinstalled all the required node packages then the above error disappeared.\r\n\r\nNow that iOS device debugging starts working it leaves the problem only on the Android.",
					"updateAuthor": {
						"name": "kenjorai",
						"key": "kenjorai",
						"displayName": "Kai Lu",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-10-04T10:22:47.000+0000",
					"updated": "2019-10-04T10:22:47.000+0000"
				},
				{
					"id": "453287",
					"author": {
						"name": "fhaque",
						"key": "fhaque",
						"displayName": "Fazlul Haque",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "[~kenjorai], Thanks for your feedback. Would you please share us details about the android issue or you can raise a different ticket for it by which we track that ticket properly? Thanks",
					"updateAuthor": {
						"name": "fhaque",
						"key": "fhaque",
						"displayName": "Fazlul Haque",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-12-23T14:47:25.000+0000",
					"updated": "2019-12-23T14:47:25.000+0000"
				}
			],
			"maxResults": 5,
			"total": 5,
			"startAt": 0
		}
	}
}