{
	"id": "144100",
	"key": "AC-730",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "8",
			"description": "",
			"name": "Needs more info"
		},
		"resolutiondate": "2015-07-03T23:43:11.000+0000",
		"created": "2015-02-03T14:20:15.000+0000",
		"labels": [
			"TCSupportTriage",
			"android",
			"studio3"
		],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "rtlechuga",
			"key": "rtlechuga",
			"displayName": "Radamantis Torres-Lechuga",
			"active": false,
			"timeZone": "Asia/Dubai"
		},
		"updated": "2016-03-08T07:36:59.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "14548",
				"name": "Titanium SDK & CLI",
				"description": "Please enter tickets related to the MobileSDK here."
			}
		],
		"description": "[INFO] :   Found Titanium module id=ti.admob version=1.0 platform=android deploy-type=test path=C:\\Users\\Bikash\\Documents\\Titanium_Studio_Workspace\\ReviewJournal\\modules\\android\\ti.admob\\1.0\r\n[ERROR] Application Installer abnormal process termination. Process exit value was 1\r\n-------------------------------\r\n\r\nI have also tested with ti.admob v2.1.2, but it creates the same issue.\r\n\r\nIf i will remove the ti.cloudpush module from the tiapp.xml file, then it is working else it throws the same error while testing using titanium stdio-> device run.\r\n",
		"attachment": [
			{
				"id": "53955",
				"filename": "tiapp.xml",
				"author": {
					"name": "bikashkumar.sundaray",
					"key": "bikashkumar.sundaray",
					"displayName": "Bikash",
					"active": true,
					"timeZone": "America/Los_Angeles"
				},
				"created": "2015-02-03T14:20:15.000+0000",
				"size": 7028,
				"mimeType": "text/xml"
			}
		],
		"flagged": false,
		"summary": "ti.cloudpush and ti.admob together creates problem",
		"creator": {
			"name": "bikashkumar.sundaray",
			"key": "bikashkumar.sundaray",
			"displayName": "Bikash",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "bikashkumar.sundaray",
			"key": "bikashkumar.sundaray",
			"displayName": "Bikash",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Windows 7, Titanium SDK v3.4.1, ti.adMob v1, ti.cloudpush v3.3.4",
		"comment": {
			"comments": [
				{
					"id": "342015",
					"author": {
						"name": "ahossain",
						"key": "ahossain",
						"displayName": "Amimul Hossain",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello We have tested the issue, We have overcome the issue with a workaround.\r\n\r\nh5. TESTING ENVIRONMENT\r\n\r\nCLI version 3.4.1, \r\nTitanium SDK version 3.5.0.GA\r\nAndroid Device\r\n\r\nh5. OBSERVATION AND WORKAROUND\r\n\r\nUsing \"ti.cloudpush\" and \"ti.admob\" together in a project causes the below error. \r\n{code}\r\n[ERROR] Application Installer abnormal process termination. Process exit value was 1\r\n[ERROR] :  Conflicting jar files detected:\r\n[ERROR] :  \r\n[ERROR] :  The following modules have different \"google-play-services.jar\" files\r\n[ERROR] :     ti.admob       (version 2.1.2) (hash=341267c94609dacf41846190d8ad3e7a)\r\n[ERROR] :     ti.cloudpush   (version 3.3.4) (hash=a9b753b4c63719e24d0022e341c57b2e)\r\n[ERROR] :  \r\n[ERROR] :  You can either select a version of these modules where the conflicting jar file is the same or you\r\n[ERROR] :  can try copying the jar file from one module's \"lib\" folder to the other module's \"lib\" folder.\r\n{code}\r\n\r\nHere we have use the  ti.admob (version 2.1.2) and ti.cloudpush (version 3.3.4). Here the error message is telling us that the \"google-play-services.jar\" file for the two modules are different. Also, recommending solution by either \"choosing a version combination for the modules where the \"google-play-services.jar\" file are same\" or copying the \"google-play-services.jar\" file from one module and replacing the \"google-play-services.jar\" file of other module with that.\r\n\r\nWe have tried this process by copying \"google-play-services.jar\" file of ti.cloudpush (version 3.3.4) module's lib folder and put it in ti.admob (version 2.1.2) modules lib folder by replacing it's own \"google-play-services.jar\" file.\r\n\r\nNow it's working and project runs smoothly. Hope this workaround helps. Thanks.\r\n",
					"updateAuthor": {
						"name": "rtlechuga",
						"key": "rtlechuga",
						"displayName": "Radamantis Torres-Lechuga",
						"active": false,
						"timeZone": "Asia/Dubai"
					},
					"created": "2015-02-04T09:28:18.000+0000",
					"updated": "2015-04-06T23:10:24.000+0000"
				},
				{
					"id": "348671",
					"author": {
						"name": "rtlechuga",
						"key": "rtlechuga",
						"displayName": "Radamantis Torres-Lechuga",
						"active": false,
						"timeZone": "Asia/Dubai"
					},
					"body": "[~bikashkumar.sundaray] pleae try the suggested workaround and let us know if that works for you\r\n",
					"updateAuthor": {
						"name": "rtlechuga",
						"key": "rtlechuga",
						"displayName": "Radamantis Torres-Lechuga",
						"active": false,
						"timeZone": "Asia/Dubai"
					},
					"created": "2015-04-06T23:10:55.000+0000",
					"updated": "2015-04-06T23:10:55.000+0000"
				}
			],
			"maxResults": 2,
			"total": 2,
			"startAt": 0
		}
	}
}