---
title: "[AC-5237] Android: [ti.geofence] UnsopportedOperationException"
---
<table>
<tr><th>GitHub Issue</th><td>n/a</td></tr>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>n/a</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Needs more info</td></tr>
<tr><th>Resolution Date</th><td>2017-10-21T19:24:48.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>n/a</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>n/a</td></tr>
<tr><th>Labels</th><td>n/a</td></tr>
<tr><th>Reporter</th><td>Brian García</td></tr>
<tr><th>Assignee</th><td>Shak Hossain</td></tr>
<tr><th>Created</th><td>2017-09-26T09:41:56.000+0000</td></tr>
<tr><th>Updated</th><td>2017-10-21T19:24:48.000+0000</td></tr>
</table>

<h3>Description</h3>

When trying to add a geofence from  6.1.0 SDK to 6.2.2.GA the following error is thrown
<code><pre>
[DEBUG] :  GeofenceModule: (main) [13,44147] Play Services is available
[DEBUG] :  GeofenceModule: (main) [6,44153] Play Services is available
[WARN] :   W/System.err: java.lang.UnsupportedOperationException
[WARN] :   W/System.err: 	at ti.geofence.GeofenceRequester.addGeofences(GeofenceRequester.java:251)
[WARN] :   W/System.err: 	at ti.geofence.GeofenceModule.startMonitoringForRegions(GeofenceModule.java:134)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1109)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:154)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
[ERROR] :  TiExceptionHandler: (main) [2,44155] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,44155] - In undefined:174,22
[ERROR] :  TiExceptionHandler: (main) [0,44155] - Message: Uncaught Java Exception occurred
[ERROR] :  TiExceptionHandler: (main) [0,44155] - Source:             geofence.startMonitoringForRegions([ geofence.createRegion({

</pre></code>


<h3>Comments</h3>

<ol>
<li>Aminul Islam 2017-09-26

   Hi,
   Thanks for reaching us. Can you be more specific about test devices version? Please add more details about test code and steps to reproduce.
   Regards,
   Aminul </li>
<li>Aminul Islam 2017-09-26

   Hi,
   We have tested  ti.geofence version: 2.0.1  with latest SDK 6.2.2.GA on android 6.0 (HTC one m8). So far we have been unable to reproduce this error.
   Success log
   <code><pre>
   [INFO] :   fetchNewFences({"lastGeolocation":{"altitude":0,"speed":0,"longitude":90.3431452,"heading":0,"latitude":23.7624935,"timestamp":1506444131535,"altitudeAccuracy":null,"accuracy":20.100000381469727}})
   </pre></code>
   Thanks 
   
   
   </li>
<li>Brian García 2017-09-28

   let me provide an example later today. I've used it together with ti.map and thus I'd to delete a play-services-base jar</li>
<li>Aminul Islam 2017-09-28

   </li>
<li>Sharif AbuDarda 2017-10-12

   Hello [~bgarcia], did you follow [~aislam]'s guide. Let me know the update of your issue.</li>
</ol>


<p><a href="/AC/AC-5237.json">JSON Source</a></p>